config/routes.rb
Rails.application.routes.draw do
  devise_for :users, path: '', path_names: {
    sign_in: 'login',
    sign_out: 'logout',
  }
  devise_scope :user do
    authenticated :user do
      root to: 'categories#index', as: :authenticated_root
    end
    unauthenticated :user do
      root to: 'splash_screen#index', as: :unauthenticated_root
    end
  end
  get 'purchases/all_purchases', to: 'purchases#all_purchases', as: 'all_purchases'

  resources :users
  resources :categories do
    resources :purchases
  end

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(current_user)
    return unless current_user.present?

    can :manage, [Category, purchase], user: current_user
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/categories.rb
class Category < ApplicationRecord
  belongs_to :user
  has_and_belongs_to_many :transactionstabels

  def transactions_sum
    transactionstabels.sum(:amount)
  end
end

app/models/categories_purchase.rb
class Categoriespurchase < ApplicationRecord
  belongs_to :category
  belongs_to :purchase
end

app/models/category.rb
class Category < ApplicationRecord
  belongs_to :user
  has_and_belongs_to_many :purchases

  validates :name, presence: true, length: { maximum: 100 }, uniqueness: { scope: :user, message: 'Category exists!' }
  validates :icon, presence: true

  def purchases_sum
    purchases.sum(:amount)
  end
end

app/models/purchase.rb
class Purchase < ApplicationRecord
  belongs_to :author, class_name: 'User', foreign_key: 'author_id'
  has_and_belongs_to_many :categories

  validates :name, presence: true, length: { maximum: 100 }
  validates :amount, presence: true, numericality: { money: true, greater_than_or_equal_to: 0 }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :categories
  has_many :purchases, foreign_key: 'author_id'

  validates :name, presence: true, length: { maximum: 100 }

  def total_budget
    purchases.sum(:amount)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :null_session
  before_action :authenticate_user!, unless: :splash_screen_controller?
  before_action :update_allowed_parameters, if: :devise_controller?

  protected

  def update_allowed_parameters
    devise_parameter_sanitizer.permit(:sign_up) do |u|
      u.permit(:name, :surname, :email, :password, :password_confirmation)
    end
    devise_parameter_sanitizer.permit(:account_update) do |u|
      u.permit(:name, :surname, :email, :password, :current_password)
    end
  end

  def splash_screen_controller?
    controller_name == 'splash_screen'
  end

  # def after_sign_out_path_for(resource_or_scope)
  #     unauthenticated_root_path
  # end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def index
    @user = current_user
    @categories = @user.categories.includes(:purchases)
  end

  def show; end

  def new
    @new_category_nav = true
    @category = Category.new
  end

  def create
    @category = Category.new(category_params)
    @category.user = current_user
    if @category.save
      flash[:success] = 'New Category added successfully!'
      redirect_to categories_path
    else
      flash.now[:error] = 'Error: Failed to add new Category!!'
      render :new, locals: { category: @category }
    end
  end

  def edit
    @category = Category.find(params[:id])
  end

  def update
    @category = Category.find(params[:id])
    if @category.update(category_params)
      flash[:success] = 'Category successfully updated.'
      redirect_to categories_path
    else
      flash.now[:error] = 'Error: Failed to update the category!'
      render :edit
    end
  end

  def destroy
    @category = Category.includes(:purchases).find(params[:id])
    @category.purchases.each(&:destroy)
    if @category.destroy
      flash[:success] = 'Category successfully deleted.'
      redirect_to categories_path
    else
      flash.now[:error] = 'Error: Failed to delete category!'
      render :index
    end
  end

  private

  def category_params
    params.require(:category).permit(:name, :icon)
  end
end

app/controllers/purchases_controller.rb
class PurchasesController < ApplicationController
  def index
    @purchases_nav = true
    @category = Category.includes(:purchases).find(params[:category_id])
    @purchases = @category.purchases.order(created_at: :desc)
  end

  def show
    @each_purchase_nav = true
    @category = Category.includes(:purchases).find(params[:category_id])
    @purchase = @category.purchases.includes(:categories).find(params[:id])
  end

  def new
    @new_purchase_nav = true
    @category = Category.find(params[:category_id])
    @purchase = Purchase.new
    @current_category_id = @category.id
  end

  def create
    @purchase = Purchase.new(purchase_params.except(:category_ids))
    @purchase.author = current_user
    @categories = Category.where(id: purchase_params[:category_ids])
    @categories.each do |category|
      @purchase.categories << category
    end
    if @purchase.save
      flash[:success] = 'Successfully added New purchase.'
      redirect_to category_purchases_path(params[:category_id])
    else
      flash.now[:error] = 'Error: Failed to Add new purchase!'
      render :new
    end
  end

  def destroy
    @purchase = current_user.purchases.find(params[:id])

    if @purchase.destroy
      flash[:success] = 'Successfully delete the purchase.'
      redirect_to category_purchases_path(params[:category_id])
    else
      flash[:error] = 'Error: Failed to delete the purchase!'
      render :show
    end
  end

  def all_purchases
    @purchases = current_user.purchases
    render 'purchases/all_purchases'
  end

  private

  def purchase_params
    params.require(:purchase).permit(:name, :amount, category_ids: [])
  end
end

app/controllers/splash_screen_controller.rb
class SplashScreenController < ApplicationController
  def index; end
end

app/controllers/user_controller.rb
class UsersController < ApplicationController
  def index; end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index; end
  # def sign_out_user
  #   sign_out(current_user)
  #   redirect_to unauthenticated_root_path
  # end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/purchases_helper.rb
module PurchasesHelper
end

app/helpers/splash_screen_helper.rb
module SplashScreenHelper
end

app/helpers/transactions_helper.rb
module TransactionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/categories/edit.html.erb
<div class="edit-object-outer-container">
  <%= link_to "Back", categories_path %>
  <h1>Update Category Page</h1>
  <%= form_with model: @category, class: "update-category-form" do |form| %>
      <div class="field">
        <%= form.label :name %>
        <%= form.text_field :name, autofocus: true, autocomplete: "name", placeholder: "e.g. Foods" %>
      </div>

      <div class="field">
        <%= form.label :icon %>
        <%= form.text_field :icon, autofocus: true, autocomplete: "icon", placeholder: "e.g. https://source.unsplash.com/user/c_v_r/100x100" %>
      </div>

      <div class="field">
        <%= form.submit "Update", class: "save-button" %>
      </div>
  <% end %>
</div>

app/views/categories/index.html.erb
<div class='categories-index verticle-flex-display'>
  <div class="categories-outer-container">
      <% @categories.each do |category| %>
        <div class='category-container verticle-flex-display'>
          <%= link_to category_purchases_url(category), class: "each-category-item horizontal-flex-display" do %>
            <div class='img-info horizontal-flex-display'>
              <%= image_tag(category.icon, alt: 'Category Icon', class: 'category-img') %>
              <div class='cat-name-at verticle-flex-display'>
                <p class='category-name'><%= category.name %> </p>
                <p class='category-at'><%= category.created_at.strftime('%d %b %Y') %></p>
              </div>
            </div>
            <p class='category-amount'>$ <%= category.purchases_sum %></p>
          <% end %>
          <div class='category-buttons'>
            <%= button_to 'UPDATE', edit_category_path(category), method: :get, class: 'update-action' %>
            <%= button_to 'DELETE', category, method: :delete, class: 'delete-action' %>
          </div>
        </div>
      <% end %>
  </div>
  <div class='add-category-outer'>
    <%= link_to "Add new Category", new_category_path(user_id: current_user), class: "add-category" %>
  </div>
</div>

app/views/categories/new.html.erb
<div class="new-object-outer-container">
  <%= form_with model: @category, class: "new-category-form verticle-flex-display" do |form| %>
      <div class='form-fields'>
      <div class="field">
        <%= form.label :name %>
        <%= form.text_field :name, autofocus: true, autocomplete: "name", placeholder: "e.g. Foods" %>
      </div>

      <div class="field">
        <%= form.label :icon %>
        <%= form.text_field :icon, autofocus: true, autocomplete: "icon", placeholder: "e.g. https://source.unsplash.com/user/c_v_r/100x100" %>
      </div>
      </div>

      <div class="field save-outer">
        <%= form.submit "Save", class: "save-button" %>
      </div>
  <% end %>
</div>

app/views/expenditures/new.html.erb
<div class="new-object-outer-container">
  <%= form_with model: @expenditure, url: category_expenditures_path, class: "add-expenditure-form verticle-flex-display" do |form| %>
    <div class='form-fields'>
      <div class="field">
        <%= form.label :name %>
        <%= form.text_field :name, autofocus: true, autocomplete: "name", placeholder: "e.g. Chocolate" %>
      </div>

      <div class="field">
        <%= form.label :amount, "Amount $" %>
        <%= form.text_field :amount, autofocus: true, autocomplete: "amount", placeholder: "e.g. 0.0" %>
      </div>

      <div class="checkboxs">
        <%= form.label :categories, 'Select Categories:' %>
        <div class='all-checkboxes'>
        <%= form.collection_check_boxes :category_ids, current_user.categories, :id, :name, { checked: @current_category_id }, include_hidden: false %>
        </div>
      </div>
    </div>

    <div class="field save-outer">
      <%= form.submit "Save", class: "save-button" %>
    </div>
  <% end %>
</div>

app/views/layouts/_navbar.html.erb
<nav>
  <% if current_page?(new_user_session_path) %>
    <div class='login-signup-nav '>
      <%= link_to raw('&#x1F860;'), current_user ? authenticated_root_path : unauthenticated_root_path, class: 'back-icon' %>
      <h1 class='nav-title'>LOGIN</h1>
    </div>
  <% elsif current_page?(new_user_registration_path) %>
    <div class='login-signup-nav'>
      <%= link_to raw('&#x1F860;'), current_user ? authenticated_root_path : unauthenticated_root_path, class: 'back-icon' %>
      <h1 class='nav-title'>REGISTER</h1>
    </div>
  <% elsif @new_category_nav %>
    <div class='new-object-nav'>
      <%= link_to raw('&#x1F860;'), categories_path, class: 'back-icon' %>
      <h1 class='nav-title'>CATEGORY</h1>
    </div>
  <% elsif @new_purchase_nav %>
    <div class='new-object-nav'>
      <%= link_to raw('&#x1F860;'), category_purchases_path(@category), class: 'back-icon' %>
      <h1 class='nav-title'>purchase</h1>
    </div>
  <% elsif @purchases_nav %>
    <div class='new-object-nav'>
      <%= link_to raw('&#x1F860;'), categories_path, class: 'back-icon' %>
      <h1 class='nav-title'>purchaseS</h1>
    </div>
  <% elsif @each_purchase_nav %>
    <div class='new-object-nav'>
      <%= link_to raw('&#x1F860;'), category_purchases_path(@category), class: 'back-icon' %>
      <h1 class='nav-title'>DETAILS</h1>
    </div>
  <% else %>
    <div class='common-nav'>
      <button id="hamburger-button">&#9776;</button>
      <div id="nav-links-container">
        <div class='ham-links'>
        <button id='home-button'><%= link_to "Home", current_user ? authenticated_root_path : unauthenticated_root_path, class: 'home-allexp-signout-links' %></button>
        <button id='allexp-button'><%= link_to "All purchases", current_user ? all_purchases_path : unauthenticated_root_path, class: 'home-allexp-signout-links' %></button>
        <% if current_user %>
          <%= button_to "Sign Out", destroy_user_session_path, method: :delete, id: 'signout-button' %>
        <% end %>
        </div>
      </div>
      <h1 id="common-nav-title">BudgetMap</h1>
    </div>
  <% end %>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ProjectBudgetApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Nunito:wght@400;700&display=swap">
    <%= javascript_importmap_tags %>
    <script src="https://code.jquery.com/jquery-3.6.4.min.js"></script>
  </head>

  <body class="verticle-flex-display">
    <% unless controller_name == 'splash_screen' && action_name == 'index' %>
      <%= render 'layouts/navbar' %>
    <% end %>
    <div class="main-container">
      <% flash.each do |name, message| -%>
        <div class="<%= name %>-flash">
          <%= message %>
        </div>
      <% end -%>
      <%= yield %>
    </div>

    <script>
      $(document).ready(function () {
        $("#hamburger-button").click(function () {
          $("#nav-links-container").fadeToggle();
        });
      });
    </script>
  </body>
</html>

app/views/purchases/all_purchases.html.erb
<div class="all-purchases-container">
    <h1 id='total-budget'>Total Budget: $<%= current_user.total_budget %></h1>

    <% @purchases.each do |purchase| %>
        <div class='purchase'>
        <p>purchase name: <%= purchase.name %></p>
        <p>purchase created at: <%= purchase.created_at.strftime('%d %b %Y') %></p>
        <p>purchase amount: <%= purchase.amount %></p>
        </div>
    <% end %>
</div>

app/views/purchases/index.html.erb
<div class="purchases-index verticle-flex-display">
  <div class='cat-name-amount'>
    <p><%= @category.name %></p>
    <p>$ <%= @category.purchases_sum %></p>
  </div>
  <div class='purchases-outer-container'>
  <% @purchases.each do |purchase| %>
    <div class='each-purchase horizontal-flex-display'>
      <div class='img-info horizontal-flex-display'>
        <%= image_tag(@category.icon, alt: 'Category Icon', class: 'category-img') %>
        <div class='exp-name-at verticle-flex-display'>
          <h3><%= link_to "#{purchase.name}", category_purchase_path(@category, purchase), class: 'purchase-name' %></h3>
          <p><%= purchase.created_at.strftime('%d %b %Y') %></p>
        </div>
      </div>
      <p class='purchase-amount'>$ <%= purchase.amount %></p>
    </div>
  <% end %>
  </div>
  <div class='add-purchase-outer'>
    <%= link_to "Add new purchase", new_category_purchase_path, class: "add-purchase" %>
  </div>
</div>

app/views/purchases/new.html.erb
<div class="new-object-outer-container">
  <%= form_with model: @purchase, url: category_purchases_path, class: "add-purchase-form verticle-flex-display" do |form| %>
    <div class='form-fields'>
      <div class="field">
        <%= form.label :name %>
        <%= form.text_field :name, autofocus: true, autocomplete: "name", placeholder: "e.g. Chocolate" %>
      </div>

      <div class="field">
        <%= form.label :amount, "Amount $" %>
        <%= form.text_field :amount, autofocus: true, autocomplete: "amount", placeholder: "e.g. 0.0" %>
      </div>

      <div class="checkboxs">
        <%= form.label :categories, 'Select Categories:' %>
        <div class='all-checkboxes'>
        <%= form.collection_check_boxes :category_ids, current_user.categories, :id, :name, { checked: @current_category_id }, include_hidden: false %>
        </div>
      </div>
    </div>

    <div class="field save-outer">
      <%= form.submit "Save", class: "save-button" %>
    </div>
  <% end %>
</div>

app/views/purchases/show.html.erb
<div class="each-purchase-container verticle-flex-display">
    <div class='purchase-info verticle-flex-display'>
        <div class='category-names'>
            <p>Categories included: </p>
            <% @purchase.categories.each do |category| %>
                <p>Category name: <%= category.name %></p>
            <% end %>
        </div>
        <p class='detaile-page-tile'>purchase name: <%= @purchase.name %></p>
        <p class='detaile-page-tile'>purchase created at: <%= @purchase.created_at.strftime('%d %b %Y') %></p>
        <p class='detaile-page-tile'>TOTAL PAYMENT: $<%= @purchase.amount %></p>
    </div>
    <div class="delete-outer">
       <%= button_to 'DELETE', category_purchase_path(@category, @purchase), method: :delete, id: 'purchase-delete-button' %>
    </div>
</div>

app/views/splash_screen/index.html.erb
<div class="splash-container verticle-flex-display">
  <div class='splash-logo-img-outer verticle-flex-display'>
    <%= image_tag("BudgetMapLogo.png", alt: "Splash-logo-img", id: "splash-img") %>
  </div>
  <div class = 'login-signup-outer verticle-flex-display'>
    <button id="login-button"><%= link_to "Login", new_user_session_path, class: 'login-signup-links' %></button>
    <button id="signup-button"><%= link_to "Sign Up", new_user_registration_path, class: 'login-signup-links' %></button>
  </div>
</div>

app/views/users/index.html.erb
<h1>Users index page</h1>